version: "3"

services:

  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - distribuidos
    command: agent -server -bootstrap-expect 1 -ui -data-dir /tmp -client=0.0.0.0

  app-config:
    image: daboca/app-config-service:v2
    platform: linux/amd64
    container_name: app-config
    ports:
      - "8888:8888"
    networks:
      - distribuidos
    depends_on:
      - consul


networks:
  distribuidos:
    external: true